# Generated by Django 6.0.2 on 2026-02-18 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_profile"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="availability",
            field=models.TextField(blank=True, help_text="e.g. 20hrs/week"),
        ),
        migrations.AddField(
            model_name="profile",
            name="is_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="profile",
            name="projects_posted_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="profile",
            name="proposals_received_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("client", "Client"),
                    ("freelancer", "Freelancer"),
                    ("admin", "Admin"),
                ],
                max_length=20,
            ),
        ),
    ]
